/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/comm.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cockpit3_WithoutInterior.geometry}
        material={nodes.Cockpit3_WithoutInterior.material}
        position={[0, 0, -3.04]}
        scale={[2.02, 1, 1]}
      />
      <mesh
        geometry={nodes['Cockpit3_WithoutInterior_(1)'].geometry}
        material={nodes['Cockpit3_WithoutInterior_(1)'].material}
        position={[2.57, 0.49, 1.79]}
        scale={[2.02, 1, 1]}
      />
      <mesh
        geometry={nodes['Cockpit3_WithoutInterior_(2)'].geometry}
        material={nodes['Cockpit3_WithoutInterior_(2)'].material}
        position={[-2.49, 0.49, 1.79]}
        scale={[2.02, 1, 1]}
      />
      <mesh
        geometry={nodes.Engine1.geometry}
        material={materials['Engine2.001']}
        position={[0.04, -1.09, -0.86]}
        scale={[1.99, 0.82, 0.82]}
      />
      <mesh
        geometry={nodes['Engine1_(2)'].geometry}
        material={nodes['Engine1_(2)'].material}
        position={[1.08, -1.45, 2.52]}
        scale={0.94}>
        <mesh
          geometry={nodes.thruster1.geometry}
          material={nodes.thruster1.material}
          position={[0, 0.25, 1.83]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.77}
        />
      </mesh>
      <mesh
        geometry={nodes['Engine1_(3)'].geometry}
        material={nodes['Engine1_(3)'].material}
        position={[-1.08, -1.45, 2.52]}
        scale={0.94}>
        <mesh
          geometry={nodes.thruster1001.geometry}
          material={nodes.thruster1001.material}
          position={[0, 0.25, 1.83]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.77}
        />
      </mesh>
      <mesh
        geometry={nodes.MainBody13.geometry}
        material={nodes.MainBody13.material}
        position={[-4.7, 0, 1.96]}
        rotation={[0, 0, -2.03]}
      />
      <mesh
        geometry={nodes.MainBody13_Mirrored.geometry}
        material={nodes.MainBody13_Mirrored.material}
        position={[4.7, 0.45, 1.96]}
        rotation={[0, 0, 1.91]}
      />
      <mesh
        geometry={nodes.MainBody2.geometry}
        material={materials['MainBody2.001']}
        position={[0, 0, 2.4]}
        scale={0.84}
      />
      <mesh geometry={nodes.Wing6.geometry} material={nodes.Wing6.material} position={[-2.5, -0.45, -0.38]} />
      <mesh
        geometry={nodes['Wing6_(1)'].geometry}
        material={nodes['Wing6_(1)'].material}
        position={[-2.5, 0.23, 2.6]}
        rotation={[0, 0.17, -0.17]}
      />
      <mesh
        geometry={nodes.Wing6_Mirrored.geometry}
        material={nodes.Wing6_Mirrored.material}
        position={[2.5, -0.45, -0.38]}
      />
      <mesh
        geometry={nodes['Wing6_Mirrored_(1)'].geometry}
        material={nodes['Wing6_Mirrored_(1)'].material}
        position={[2.5, 0.23, 2.6]}
        rotation={[0, -0.17, 0.17]}
      />
    </group>
  )
}

useGLTF.preload('/comm.glb')
